framework:
  messenger:
    transports:
      async:
        dsn: "doctrine://default?queue_name=async"
        options:
          table_name: messenger_messages
    routing:
      'App\Message\ConvertFileMessage': async
